sudo: required
services:
        - docker
before_install:
        - docker build -t reg1reg1/docker-ci-cd -f Dockerfile.dev .
script:
        - docker run -e CI=true reg1reg1/docker-ci-cd npm run test -- --coverage
deploy:
        provider: elasticbeanstalk
        region: "us-east-2"
        app: "dockeri-ci-cd"
        env: "DockerCiCd-env"
        bucket_name: "elasticbeanstalk-us-east-2-502659215395"
        bucket_path: "docker-ci-cd"
        on:
                branch: master
        access_key_id: $AWS_ACCESS_KEY
        secret_access_key: 
                secure: "$AWS_SECRET_KEY" 
